package net.sf.ohla.rti.federate;

public enum TimeAdvanceType
{
  NONE, TIME_ADVANCE_REQUEST, TIME_ADVANCE_REQUEST_AVAILABLE,
  NEXT_MESSAGE_REQUEST, NEXT_MESSAGE_REQUEST_AVAILABLE,
  FLUSH_QUEUE_REQUEST
}
